language: java
jdk: oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Jh1MQKIRYi93UCGI8To-4g"


script: ./gradlew -s -Dorg.gradle.daemon=false build

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  coverity_scan:
    project:
      name: "cdancy/api-processor"
      description: "generic java api processor"
    notification_email: christoforever@gmail.com
    build_command:  ./gradlew -s -Dorg.gradle.daemon=false build
    branch_pattern: coverity_scan
